// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjkd1gFzR0BbcFXVDg95JEIGtSwdjlqe4',
    appId: '1:142081445307:web:c1dd3c391458e7b6d4089e',
    messagingSenderId: '142081445307',
    projectId: 'chatapp-aa117',
    authDomain: 'chatapp-aa117.firebaseapp.com',
    storageBucket: 'chatapp-aa117.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEI_15WuZk7bmKJjYeSCiMIvOCEp5hbTo',
    appId: '1:142081445307:android:81635d11614d89afd4089e',
    messagingSenderId: '142081445307',
    projectId: 'chatapp-aa117',
    storageBucket: 'chatapp-aa117.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxjrAdO-0FnCpgRXh05SEO_yyrlNZPcoE',
    appId: '1:142081445307:ios:41c7324e29be0ea9d4089e',
    messagingSenderId: '142081445307',
    projectId: 'chatapp-aa117',
    storageBucket: 'chatapp-aa117.appspot.com',
    iosBundleId: 'com.example.demoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxjrAdO-0FnCpgRXh05SEO_yyrlNZPcoE',
    appId: '1:142081445307:ios:41c7324e29be0ea9d4089e',
    messagingSenderId: '142081445307',
    projectId: 'chatapp-aa117',
    storageBucket: 'chatapp-aa117.appspot.com',
    iosBundleId: 'com.example.demoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjkd1gFzR0BbcFXVDg95JEIGtSwdjlqe4',
    appId: '1:142081445307:web:f0e862d6c92536d9d4089e',
    messagingSenderId: '142081445307',
    projectId: 'chatapp-aa117',
    authDomain: 'chatapp-aa117.firebaseapp.com',
    storageBucket: 'chatapp-aa117.appspot.com',
  );
}
